RUCAIBox/RecBole

- recbole/data/dataloader/general_dataloader.py
- recbole/data/dataloader/neg_sample_mixin.py
- recbole/data/dataloader/sequential_dataloader.py
- recbole/evaluator/abstract_evaluator.py
- recbole/evaluator/loss_evaluator.py
- recbole/evaluator/topk_evaluator.py
- recbole/trainer/trainer.py
- recbole/utils/utils.py
1. bug fix in trainer (runtime error when epoch == 0)
2. refactor _generate_train_loss_output in Trainer
3. parameters & comments fix in abstract_evaluator.py
4. docs format: pos_len_list must be np.ndarray
5. commits format && code format in evaluator
6. improve get_model() in utils.py
> FIX: Bug fix, code format && comments format

- recbole/data/dataloader/sequential_dataloader.py
I have added the function as we discussed, and confirm that the feature loaded is correct.
The only issue is, I have not decided how to add SEQ features of the history items, say a number of comments for several movies in the Moview-Len. I am not sure about two aspects:
1. Whether we need to define the max length of token sequences
2. Whether we need to represent the history sequences as a 2D or 3D tensor.
> FEA: Add Interaction features of the history items for sequential dataloader 

- recbole/data/dataloader/general_dataloader.py
- recbole/data/dataset/dataset.py
- recbole/data/utils.py
- recbole/evaluator/abstract_evaluator.py
- recbole/evaluator/evaluators.py
- recbole/evaluator/metrics.py
- recbole/evaluator/proxy_evaluator.py
- recbole/model/knowledge_aware_recommender/kgat.py
- recbole/trainer/trainer.py
- tests/metrics/test_rank_metrics.py
1.Individual Evaluator can't raise NotImplementedError when used with eval_setting is full.
2.metrics may be disordered in log information.
3.GAUC will be calculated by error when there are items with same predicted scores for one user.
> FIX: bugs in evaluator

- recbole/data/dataset/sequential_dataset.py
I assume [this issue](https://github.com/RUCAIBox/RecBole/issues/620) been done but it seems not yet. Sorry for the late response.
Just a quick confirmation that I found the `self.uid_list` for individual data_loader are different, and it covers the indices number for a specific phase, so I directly apply  `local_inter_feat = self.inter_feat[self.uid_list]` to get the interaction matrix for the specific phase, correct me if I am wrong.
> update fetch interaction matrix of sequential dataset

- recbole/config/eval_setting.py
- recbole/data/dataloader/general_dataloader.py
1. Change self.group_by into self.group_field.
2. Fix runtime error when ContextFullDataLoader is empty.
> FIX: fix runtime error when ContextFullDataLoader is empty

- recbole/model/general_recommender/__init__.py
I added your RaCT model to the init file so that it is importable like the other models:
```python
from recbole.model.general_recommender import RaCT
````
It was not yet included, but the model works so I guess I can call this a bugfix 😄
> Bugfix: add RaCT to __init__.py

- .github/workflows/python-package.yml
I think it's nice to be able to run the test manually and on push by adding the `on event` in the github action.
> It's nice to be able to run the CI manually and on push 

- recbole/data/dataset/dataset.py
When error, the message is not clear. 
I added a message to show which token is not found in which field. This can help users to identify their errors quickly.
> Cleared the error message

- README.md
In the RecBole repo, there has a way to find the best hyperparameters for different models and datasets by running "run_hyper.py". But now it lacks of some illustration how to use it in README.md, so I add this part to README.md to meet the needs of some people.
> Add the usage information of auto-tuning tools in README.md

- recbole/data/dataset/dataset.py
- recbole/properties/dataset/url.yaml
- recbole/utils/url.py
- run_example/session_based_rec_example.py
An example for running session-based recommendation benchmarks (diginetica, Tmall and Nowplaying). The processed benchmarks are taken from the [GCE-GNN Repo](https://github.com/CCIIPLab/GCE-GNN), then converted into atomic files. #617 #766
> FEA: example for running session-based rec benchmarks

- recbole/config/configurator.py
- recbole/evaluator/evaluator.py
- recbole/evaluator/register.py
- recbole/model/context_aware_recommender/xdeepfm.py
- recbole/model/layers.py
- recbole/trainer/trainer.py
- recbole/utils/enum_type.py
1.Fix issue #935 and bug in xDeepFM.
2.Rename EvaluatorType to `VALUE`
> Rename EvaluatorType & FIX: bugs in model

- .github/workflows/python-package.yml
- docs/source/developer_guide/customize_metrics.rst
- recbole/config/configurator.py
- recbole/evaluator/base_metric.py
- recbole/evaluator/evaluator.py
- recbole/evaluator/metrics.py
- recbole/evaluator/register.py
- tests/config/run.sh
- tests/metrics/test_loss_metrics.py
- tests/metrics/test_topk_metrics.py
1.The user only needs to create a class when adding a metric, and no other code needs to be modified.
2.Improved the document of customizing metrics.
3.Update the configurator and fix bugs.
**to be reviewd by @linzihan-backforward**
> FEA: easier to implement a metric

- .gitignore
- recbole/properties/overall.yaml
- recbole/trainer/trainer.py
- recbole/utils/__init__.py
- recbole/utils/argument_list.py
- recbole/utils/wandblogger.py
This PR adds support for [Weights and Biases](https://wandb.ai/site) experiment tracking (metric logging).
I have tested the implementation using the quick start provided with this repo. We can start logging metrics to W&B by passing `--log_wandb=True` as command line argument, or use config dict. One can also turn `log_wandb: True` in the `overall.yaml` file or provide it as external config file. 
```
python run_recbole.py --epochs=10 --log_wandb=True
```
* Able to easily share the experiments. Here's an [example W&B run](https://wandb.ai/ayush-thakur/recbole/runs/es3wyf9j?workspace=user-ayut) that shows train and valid metrics from generated by running the quick start. 
* Ability to check out the exact configuration used to train the model. Configs can thus be easily compared across …
> Add Weights and Biases Integration

- recbole/data/dataset/dataset.py
- recbole/properties/overall.yaml
To save filtered dataset and split dataloaders, I set parameter `save_dataset=True ` and parameter `save_dataloaders=True`, as suggested in [https://recbole.io/docs/user_guide/config/environment_settings.html](https://recbole.io/docs/user_guide/config/environment_settings.html) and [https://recbole.io/docs/user_guide/usage/save_and_load_data_and_model.html](https://recbole.io/docs/user_guide/usage/save_and_load_data_and_model.html). 
But it occurs some bugs which show that the directory of `self.config['checkpoint_dir']` does not exist. So I check the corresponding source code of `save` function to add a few lines of code to automatically make save dir if it does not exist.
> fix save dir of dataset bugs

- recbole/model/general_recommender/lightgcn.py
- recbole/model/general_recommender/ncl.py
- recbole/model/general_recommender/ngcf.py
- recbole/model/general_recommender/sgl.py
When running LightGCN, NGCF and NCL, there will be a UserWarning as follows:
```
UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor.
```
The reason is that in `get_norm_adj_mat`, the type of `L.row` and `L.col` is `numpy.ndarray`, so `i =torch.LongTensor(np.array([row, col]))` creates a tensor from a list of numpy.ndarrays.
https://github.com/RUCAIBox/RecBole/blob/4f761699454fd5d8873607173d2514d38ac24031/recbole/model/general_recommender/lightgcn.py#L99-L103
In SGL, `numpy.ndarray` is converted to `list` by `.tolist()` to avoid the warning.
https://github.com/RUCAIBox/RecBole/blob/4f761699454fd5d8873607173d2514d38ac24031/recbole/model/general_recommend …
> FIX: fix UserWarning in get_norm_adj_mat and accelerate csr2tensor

- docs/source/user_guide/config/training_settings.rst
- recbole/model/context_aware_recommender/afm.py
- recbole/model/context_aware_recommender/autoint.py
- recbole/model/context_aware_recommender/dcn.py
- recbole/model/context_aware_recommender/deepfm.py
- recbole/model/context_aware_recommender/dssm.py
- recbole/model/context_aware_recommender/ffm.py
- recbole/model/context_aware_recommender/fm.py
- recbole/model/context_aware_recommender/fnn.py
- recbole/model/context_aware_recommender/fwfm.py
- recbole/model/context_aware_recommender/lr.py
- recbole/model/context_aware_recommender/nfm.py
- recbole/model/context_aware_recommender/pnn.py
- recbole/model/context_aware_recommender/widedeep.py
- recbole/model/context_aware_recommender/xdeepfm.py
- recbole/model/general_recommender/cdae.py
- recbole/model/general_recommender/dmf.py
- recbole/model/general_recommender/fism.py
- recbole/model/general_recommender/nais.py
- recbole/model/general_recommender/neumf.py
- recbole/model/general_recommender/nncf.py
- recbole/model/sequential_recommender/dien.py
- recbole/model/sequential_recommender/din.py
- recbole/model/sequential_recommender/s3rec.py
- recbole/properties/overall.yaml
- recbole/trainer/trainer.py
FEA: add mixed precision training
> FEA: Add Mixed accuracy training

- docs/source/user_guide/usage/use_modules.rst
Hi 
When I added ItemCoverage to my metrics config and ran trainer.evaluate from checkpoint, I got the following error.
```
Traceback (most recent call last):
File "src/tools/evaluate_only.py", line 156, in <module>
main()
File "/home/yusuke-fukasawa/.cache/pypoetry/virtualenvs/teller-novel-recbole-nYDNORo--py3.8/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
return self.main(*args, **kwargs)
File "/home/yusuke-fukasawa/.cache/pypoetry/virtualenvs/teller-novel-recbole-nYDNORo--py3.8/lib/python3.8/site-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/home/yusuke-fukasawa/.cache/pypoetry/virtualenvs/teller-novel-recbole-nYDNORo--py3.8/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
return ctx.invoke(self.callback, **ctx.params) …
```
> Docs: Insert eval_collector.data_collect when evaluate from checkpoint (calculate ItemCoverage)

- recbole/model/abstract_recommender.py
- recbole/model/general_recommender/cdae.py
- recbole/model/general_recommender/macridvae.py
- recbole/model/general_recommender/multidae.py
- recbole/model/general_recommender/multivae.py
- recbole/model/general_recommender/ract.py
- recbole/model/general_recommender/recvae.py
Hi. I'm a newbie to Recbole. When I try to use autoencoder method Mult-VAE on Movielens-20m with GPU, OOM issue keeps coming up.
After I check the code, I noticed that several autoencoder methods (cdae, macridvae, multidae, multivae, ract, recvae) will load all the interaction in training set to cuda in `__init__`, and this requires lots of memory for dataset with tens of millions interactions.
So I think maybe it's a good idea that we do not set history items to cuda, and only set rating matrix to cuda when `get_rating_matrix` is called. This way, I can run movielens-20m on Tesla k80 easily.
And since these AutoEncoders share same behavior, so I create a Mixin class that all these auto encoders can inherit.
Below is a simple speed test, I run mult-vae on Movielens-100k, with both CPU …
> Change to cuda behavior for autoencoder models

- recbole/properties/dataset/url.yaml
Credit to Marta @mmosc and Andreas, thanks!
Include a new dataset named Music4All-Onion, original contributed by Moscati et al. "Music4All-Onion -- A Large-Scale Multi-faceted Content-Centric Music Recommendation Dataset." CIKM 2022, Resource Track.
Files have been processed into atomic files and uploaded to [Google Drive](https://drive.google.com/drive/folders/1so0lckI6N6_niVEYaBu-LIcpOdZf99kj?usp=sharing). Besides, downloading link has been added by indicating dataset as `music4all-onion`.
> Include Music4All-Onion dataset

- run_example/recbole-using-all-items-for-prediction.ipynb
Improve the performance of recbole-using-all-items-for-prediction.ipynb
In practice, I found that the operation of the code in this file was very time-consuming in the prediction task. After debugging, I found that the access time of dataset[index] took a large proportion. When dataset is large, index would be a bool array with the same size as dataset. So I first selected the corresponding subscript, directly take out the corresponding element in the dataset, which will greatly improve 10 times of the performance on ml-100k dataset.
> FIX: improve the performance of accessing dataset

- recbole/properties/dataset/url.yaml
Credit to Wei @ChandlerBang, Haitao @HaitaoMao, et al., thanks!
Include a new dataset named **Amazon-M2**, originally contributed by Wei et al. "Amazon-M2: A Multilingual Multi-locale Shopping Session Dataset for Recommendation and Text Generation." [[arXiv](https://arxiv.org/abs/2307.09688)], which has been used in the [Amazon KDD Cup '23: Multilingual Recommendation Challenge](https://www.aicrowd.com/challenges/amazon-kdd-cup-23-multilingual-recommendation-challenge).
Files have been processed into atomic files and uploaded to [Google Drive](https://drive.google.com/drive/folders/16NIkXd5KerLeBifW0cuIeVZ33vzjYOz8?usp=drive_link). Besides, downloading link has been added by indicating the dataset as `amazon-m2`.
> Include Amazon-M2 dataset [KDD Cup 2023]

- recbole/data/dataloader/abstract_dataloader.py
In the current version
https://github.com/RUCAIBox/RecBole/blob/2c6f066eb1e87814bb5101eb727b1308661e030c/recbole/data/dataloader/abstract_dataloader.py#L139-L140
The `if` condition is still `true` when `distribution` is `uniform` but `sample_num` is `none`.
> [🐛Bug] Fix `if` condition in `set_neg_sample_args` function

- docs/source/get_started/distributed_training.rst
- recbole/quick_start/__init__.py
- recbole/quick_start/quick_start.py
- run_recbole.py
- run_recbole_group.py
- significance_test.py
We are unable to collect results directly from `mp.spawn`, e.g., 
https://github.com/RUCAIBox/RecBole/blob/96eb311b029c0a399df452cbc612460e8f87d44e/run_recbole_group.py#L25-L38
[torch.multiprocessing.Queue](https://pytorch.org/docs/stable/notes/multiprocessing.html#reuse-buffers-passed-through-a-queue) can be applied for this purpose.
1. Fixd result collection bug when using `mp.spawn`;
2. Updated documents of `distributed training`;
3. Fix bugs in [significance_test.py](https://github.com/RUCAIBox/RecBole/blob/master/significance_test.py)
> [🐛 BUG] Fix bugs when collecting results from `mp.spawn` in multi-GPU training

- README.md
- README_CN.md
- conda/conda_release.sh
- conda/meta.yaml
- docs/source/conf.py
- docs/source/index.rst
- recbole/__init__.py
- recbole/model/general_recommender/ldiffrec.py
- recbole/quick_start/quick_start.py
- requirements.txt
- setup.py
- update README.md: add v1.2.0 news, version info, leader info, cite
- update requirements.txt
- update meta.yaml and setup.py
- update ldiffrec.py: change kmeans-pytorch import position
> FIX: update version information

- recbole/model/sequential_recommender/__init__.py
- recbole/model/sequential_recommender/gru4reccpr.py
- recbole/model/sequential_recommender/repeatnet.py
- recbole/model/sequential_recommender/sasreccpr.py
- recbole/properties/model/GRU4RecCPR.yaml
- recbole/properties/model/SASRecCPR.yaml
- tests/model/test_model_auto.py
The code is modified from https://github.com/iesl/softmax_CPR_recommend
> Integrate softmax cpr to the latest RecBole version

- recbole/model/general_recommender/ngcf.py
- recbole/model/general_recommender/simplex.py
- recbole/model/knowledge_aware_recommender/mkr.py
- recbole/model/sequential_recommender/gru4reckg.py
- recbole/properties/model/SimpleX.yaml
Some models were directly instantiating a dropout object in the forward function, such as NGCF. Calling model.eval() does not turn off dropout in these scenarios, leading to potential issues in the case a direct access to the forward function is done for whatever use.
For one of my projects, I indeed needed to regenerate the user and item embeddings by keeping constant the trained weights, but the predictions were inconsistent due to this issue.
I found this issue in NGCF and GRU4RecKG. While checking all the models, I also noticed that the dropout probability for SimpleX was hard-coded as 0.1, and I moved it to its config file.
> Fixed dropout instantiation in NGCF and GRU4RecKG forward. Moved dropout_prob in config for SimpleX.

- recbole/evaluator/collector.py
只在最终get_data_struct将tensor转移到cpu，极大节约cpu占用。
> fix: only use .cpu() in the final step in collector.py to reduce the usage of cpu

- asset/model_list.json
- docs/source/recbole/recbole.model.general_recommender.asymknn.rst
- docs/source/recbole/recbole.model.general_recommender.rst
- docs/source/user_guide/model/general/asymknn.rst
- docs/source/user_guide/model_intro.rst
- recbole/model/general_recommender/__init__.py
- recbole/model/general_recommender/asymknn.py
- recbole/model/general_recommender/itemknn.py
- recbole/properties/model/AsymKNN.yaml
- recbole/properties/model/ItemKNN.yaml
- tests/model/test_model_auto.py
- Implemented user-based and item-based asymmetric KNN versions as described in [Aiolli (2013)](https://dl.acm.org/doi/pdf/10.1145/2507157.2507189)
- Updated the documentation and introduced the following parameters:
- knn_method (str): [item, user]
Specifies whether to use user-based or item-based KNN
- k (int):
Neighborhood size
- alpha (float): [0, 1]
Weight parameter for asymmetric cosine similarity
- beta (float): [0, 1]
Final score balance parameter
- q (int):
Exponent for the "locality of scoring function"
Created this algorothms for my researches. I'm happy for feedback and improvements!
> [feature] AsymKNN for user and item based KNN

- config.yaml
- recbole/data/dataset/dataset.py
Add time-based split mode with ratios in evaluation.
References:
[https://arxiv.org/abs/2408.12008](https://arxiv.org/abs/2408.12008)
[https://dl.acm.org/doi/10.1145/3604915.3608839](https://dl.acm.org/doi/10.1145/3604915.3608839)
> [Feature] Time-based split in evaluation

- docs/source/recbole/recbole.model.general_recommender.als.rst
- docs/source/user_guide/model/general/als.rst
- recbole/model/general_recommender/als.py
- recbole/properties/model/ALS.yaml
- recbole/trainer/trainer.py
NOTE: this feature uses an external library [implicit](https://benfred.github.io/implicit/), similar to the implementations of [LightGBM](https://recbole.io/docs/user_guide/model/context/lightgbm.html) and [XGBoost](https://recbole.io/docs/user_guide/model/context/xgboost.html).  
Implemented external ALS matrix factorization algorithm using [ALS implicit](https://benfred.github.io/implicit/api/models/cpu/als.html). The original work has been done by Koren in [Collaborative Filtering for Implicit Feedback Datasets](http://yifanhu.net/PUB/cf.pdf) and performance optimization in [Applications of the Conjugate Gradient Method for Implicit Feedback Collaborative Filtering](https://dl.acm.org/doi/pdf/10.1145/2043932.2043987).
Updated the documentation and introduced the following parameters:
- …
> [feature] ALS Matrix Factorization using External Library (implicit)
