recbole/data/utils.py
recbole/sampler/sampler.py

config['training_neg_sample_distribution'] = uniform(default) or popularity can control this feature

FEA:  allow training phase to choose neg_sample distribution

---

recbole/trainer/trainer.py

FIX: bug fix in trainer._full_sort_batch_eval() 

---

recbole/model/general_recommender/gcmc.py
recbole/model/general_recommender/lightgcn.py
recbole/model/general_recommender/spectralcf.py

FIX: improve the efficiency of GCMC/LightGCN/SpectralCF

---

recbole/data/dataloader/abstract_dataloader.py
recbole/data/dataloader/general_dataloader.py
recbole/data/dataloader/sequential_dataloader.py
recbole/evaluator/topk_evaluator.py
recbole/trainer/trainer.py

1. Add upgrade_batch_size to abstract_dataloader.py && change usage of set_batch_size to upgrade_batch_size.
2. Refactor in full sort && speed up in general full sort predict.

FEA: refactor in full sort.

---

recbole/data/dataloader/general_dataloader.py
recbole/data/dataset/dataset.py
recbole/data/utils.py

1. Add config['benchmark_filename'] to load pre-split dataset.
2. Increased the robustness of GeneralFullDataLoader, which can handle empty dataset now.

FEA: Add config['benchmark_filename'] to load pre-split dataset.

---

recbole/data/dataloader/general_dataloader.py
recbole/trainer/trainer.py

1. Increased the robustness of trainer.evaluate
2. Bug fix in GeneralFullDataLoader.

FEA: Increased the robustness of trainer.evaluate && bug fix in GeneralFullDataLoader.

---

recbole/properties/overall.yaml
recbole/quick_start/quick_start.py
recbole/trainer/trainer.py
recbole/utils/argument_list.py
recbole/utils/case_study.py

1. Add case_study.py (resolve #506)
2. Add progress bar to trainer.py (resolve #516)
3. Add callback function hook for end of training an epoch (resolve #517)

FEA: Add three new features

---

recbole/model/sequential_recommender/bert4rec.py
tests/model/test_model_auto.py
tests/model/test_model_manual.py

1. REFACTOR: Move tests in test_model_manual.py to test_model_auto.py
2. FIX: device error in BERT4Rec (from master branch)

REFACTOR: refactor in test_model

---

recbole/config/eval_setting.py
recbole/data/dataloader/sequential_dataloader.py
recbole/data/dataset/sequential_dataset.py
recbole/data/utils.py

1. Add set_ordering_and_splitting to eval_setting.py
2. Add a check to ordering_args, group_field and split_args in sequential dataset.

FEA: Improvment in ordering_args, group_field and split_args

---

recbole/config/configurator.py
recbole/properties/overall.yaml
recbole/trainer/trainer.py

1. add `valid_metric_bigger` to overall.yaml
2. fix the bugs when we use smaller, better metrics

FIX: config & trainer

---

recbole/data/dataset/kg_dataset.py

fix the bug of len(kg_dataset.field2id_token['item_id']) != len(kg_dataset.field2id_token['item_id']).

FIX: fix the bug in issue #823

---

recbole/utils/url.py

1. Log error;
2. Rename error for README.md

FIX: bugs of datasets auto-downloading

---

recbole/data/dataset/dataset.py
recbole/data/dataset/sequential_dataset.py
recbole/properties/dataset/sample.yaml
recbole/properties/overall.yaml
recbole/sampler/sampler.py
recbole/utils/argument_list.py
tests/config/test_config.py
tests/config/test_overall.py
tests/data/seq_benchmark/seq_benchmark.test.inter
tests/data/seq_benchmark/seq_benchmark.train.inter
tests/data/seq_benchmark/seq_benchmark.valid.inter
tests/data/test_dataset.py
tests/model/test_model.yaml

1. Add split by ratio for sequential dataset (#718 );
2. Add benchmark loading for sequential dataset (#700 #766 );
3. Update argument list;
4. remove useless args;

FEA: RS, benchmark for seq-rec & FIX: update argument_list

---

recbole/trainer/trainer.py

FIX: fix cuda out of memory when `item_feat` is loaded.

---

docs/source/user_guide/config/training_settings.rst
recbole/model/general_recommender/lightgcn.py
recbole/model/loss.py
recbole/properties/overall.yaml

FIX: add require_pow in EmbLoss

---

recbole/data/dataloader/general_dataloader.py
recbole/utils/logger.py

I made a lot of experments, it make log dir have many log file. 
Maybe using model name to category experments much better?

UPD: Experments Log Enhance.

---

recbole/data/interaction.py

FIX: bug fix in `Interaction` when input tensor is 0-d tensor. (fix for #1187)

---

recbole/trainer/trainer.py
requirements.txt
tests/config/test_overall.py

FEA: add test cases and add mixd precision training on CPU

FEA: add test cases and add mixd precision training on CPU

---

recbole/quick_start/quick_start.py
recbole/utils/__init__.py
recbole/utils/utils.py
requirements.txt

FEA: implement counting of FLOPs

FEA: implement counting of FLOPs

---

.github/workflows/python-package.yml
docs/source/user_guide/config/training_settings.rst
docs/source/user_guide/usage/parameter_tuning.rst
run_hyper.py
run_test.sh
tests/hyper_tuning/test_hyper_tuning.py
tests/hyper_tuning/test_hyper_tuning_config.yaml
tests/hyper_tuning/test_hyper_tuning_params.yaml

FEA: tests for hyper-tuning

---

recbole/config/configurator.py

FEA: warning for neg_sampling parameter

FEA: warning for neg_sampling parameter

---

recbole/config/configurator.py
recbole/data/transform.py
recbole/data/utils.py
recbole/properties/overall.yaml
recbole/sampler/sampler.py
tests/config/test_config.py
tests/model/test_model_auto.py

FEA: add alpha parameter for popularity sampling distribution

FEA: add alpha parameter for popularity sampling distribution

---

recbole/quick_start/quick_start.py
recbole/utils/utils.py

FIX: transform bug in get_flops

FIX: transform bug in get_flops

---

recbole/data/dataset/dataset.py
recbole/model/general_recommender/simplex.py
recbole/trainer/hyper_tuning.py
run_hyper.py

Modified the interaction history matrix generation function to support setting the maximum number of history interaction records.  And apply the latest function `history_item_matrix` to the SimpleX model.

Update the funtion of history_item_matrix

---

docs/source/developer_guide/customize_trainers.rst
docs/source/user_guide/usage/parameter_tuning.rst

FIX: fix description of Mixed Precision Training and Ray

FIX: fix description of Mixed Precision Training and Ray

---

docs/source/user_guide/usage/parameter_tuning.rst
run_hyper.py

FIX: get parameter from file & add gpu in ray tuning

FIX: get parameter from file & add gpu in ray tuning

---

docs/source/developer_guide/customize_trainers.rst

FIX: explains models that does not support mixed precision training

---

recbole/data/utils.py

FIX: bug in alpha parameter for eval sampler

FIX: bug in alpha parameter for eval sampler

---

recbole/utils/url.py

Fix https://github.com/RUCAIBox/NCL/issues/20.

FIX: bugs on the suffix of dataset downloading

---

docs/source/get_started/distributed_training.rst
docs/source/get_started/started/context-aware.rst
docs/source/get_started/started/general.rst
docs/source/get_started/started/sequential.rst
docs/source/user_guide/usage/running_different_models.rst

FIX: Update docs of train_neg_sample_args parameter

FIX: Update docs of train_neg_sample_args parameter

---

recbole/data/dataloader/general_dataloader.py
recbole/data/dataset/dataset.py
recbole/data/utils.py

Fix: fix saving and loading for datasets and dataloaders (#1697)

---

recbole/model/abstract_recommender.py

removing unused argument from documentation in abstract_recommender.py

---

recbole/model/abstract_recommender.py

Convert tensors into the correct gpu/cpu device in `AutoEncoderMixin`

[🐛BUG]: Convert tensors into the correct device

---

recbole/model/general_recommender/pop.py
recbole/trainer/trainer.py

FIX(trainer.py): RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:x and cpu!

FIX(trainer.py):calculate_loss error when use multi-gpu

---

docs/source/user_guide/usage/use_modules.rst

- train_data.dataset should be in place of train_data

fix: argument value in automatic selection of model

---

conda/meta.yaml

Update conda config
